### ISSUE TITLE
Why do I need this script ?

### ISSUE THREAD

**Issue by Fr33maan** [juliengk/csf-post-docker#10]
As title say, why do we need to have additional configuration when working with docker ? 

[This](https://jsherz.com/docker/configserver/firewall/iptables/csf/debian/systemd/2016/05/16/configuring-configserver-firewall-for-docker.html) might be an explanation

Thanks for your answer

**Comment by ghost** [comment]
what do you mean additional configuration?

**Comment by Fr33maan** [comment]
I mean that your script will do additional stuff. I don't understand why we need to do this if we use Docker and CSF together

**Comment by Fr33maan** [comment]
In simpler words: Why do I need this script ?

**Comment by ghost** [comment]
Which additional stuff? You might need that script if you restart csf for example. All the rules added by Docker will disapear!

**Comment by Fr33maan** [comment]
Forget about "additional", your script does stuff that nothing else does.
So if I restart CSF without restarting docker service, all rules will be dropped that's it ? 
I'm sorry for my ignorance, I'm a newcomer to Docker world.

**Comment by ghost** [comment]
yes

**Comment by Fr33maan** [comment]
And if I restart Docker service everytime I restart CSF then I don't need the script ?

**Comment by ghost** [comment]
Yes. Then disable CSF auto update. Otherwise that might happen in the middle of the night :)

**Comment by Fr33maan** [comment]
Thanks for those crystal clear explanations ! Do you agree if I include your scripts in [Armourer](https://github.com/l1br3/armourer) ?

**Comment by ghost** [comment]
The script has not been updated for a while now. Docker change a lot and the script needs to be updated accordingly.

**Comment by Fr33maan** [comment]
Do you mean that it is actually not usable ?

**Comment by ghost** [comment]
it is

**Comment by ghost** [comment]
i got a question about Armourer.

Tu parles francais?

**Comment by Fr33maan** [comment]
Feel free to open an issue or find me on gitter @l1br3
