### ISSUE TITLE
Problem with docker bridges (br-*)

### ISSUE THREAD

**Issue by Tw1nh34d** [juliengk/csf-post-docker#14]
For bridges with name like **br-9d7af61d6835** the script is not substituting the $bridge variable.
It is reproducable on the cli:

_> docker network ls -q --filter='Driver=bridge'
d79a1bf7d01a
**9d7af61d6835** <--
74e6a74405a2

_> docker network inspect -f '{{"br-$bridge" | or (index .Options "com.docker.network.bridge.name")}}' 9d7af61d6835
**br-$bridge**

A check of bridges with a name "com.docker.network.bridge.name" is possible:
_> docker network inspect -f '{{"br-$bridge" | or (index .Options "com.docker.network.bridge.name")}}' d79a1bf7d01a
docker0

Only a minor change is needed to fix this issue:
docker network inspect -f '{{**"'br-$bridge'"** | or (index .Options "com.docker.network.bridge.name")}}'

**Comment by juliengk** [comment]
if you run the command in your terminal without exporting the $bridge var and not specifying the network name on the command `docker network inspect` it will not work
